language: node_js
node_js:
  - node

cache: yarn

script:
  - ./bin/run --version
  - ./bin/run --help
  - yarn lint
  - yarn test

after_success:
  - ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
  - ./node_modules/.bin/codecov
