pool:
  vmImage: 'ubuntu-latest'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
- script: yarn --frozen-lockfile
  displayName: Install dependencies

- script: yarn lint
  displayName: Lint

- script: yarn test
  displayName: Test

- script: yarn nyc report --reporter text-lcov > coverage.lcov
  condition: not(variables['System.PullRequest.IsFork'])
  displayName: Report code coverage

- script: yarn codecov --token $CODECOV_TOKEN
  condition: not(variables['System.PullRequest.IsFork'])
  displayName: Upload code coverage
  inputs:
    env:
      CODECOV_TOKEN: $(CODECOV_TOKEN)
