pool:
  vmImage: 'ubuntu-latest'

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
- script: yarn --frozen-lockfile
  displayName: Install dependencies

- script: yarn lint
  displayName: Lint

- script: yarn test
  displayName: Test

- script: yarn nyc report --reporter text-lcov > coverage.lcov
  displayName: Report code coverage

- script: yarn codecov --token $CODECOV_TOKEN
  displayName: Upload code coverage
